#!/bin/bash
# LGSM fn_install_serverdir function
# Author: Daniel Gibbs
# Website: http://gameservermanagers.com
# Version: 240515

echo ""
echo "Server Directory"
echo "================================="
echo ""
pwd
echo ""
if [ -d "${filesdir}" ]; then
	fn_printwarningnl "A server is already installed here."
fi
